name: NPCPlugin
version: '${project.version}'
main: lkc.npcplugin.NPCPlugin
api-version: 1.18
depend: [ Citizens ]
softdepend: [ httpconnection ]
commands:
  settingnpc:
    description: npc μ„Έν…
    usage: /<command>
