name: httpconnection
version: '${project.version}'
main: lkc.httpconnection.httpconnection
api-version: 1.18
softdepend: [ event ]
commands:
  gethttp:
    usage: /<command> <topic> <payload>
    description: Send a payload to an http topic