name: httpconnection
version: '0.1.0'
main: lkc.httpconnection.httpconnection
api-version: 1.18

commands:
  gethttp:
    usage: /<command> <topic> <payload>
    description: Send a payload to an http topic