name: Letterbuild
version: '${project.version}'
main: lkc.letterbuild.Letterbuild
api-version: 1.18
commands:
  letter:
    usage: /<command> <option> <instance>
    description: <option> -> (list, help, build) / <instance> -> help참조
